@startgantt
printscale weekly
Project starts 2026-05-01
Project ends 2026-09-04

-- Task Name --
[Literature Review] starts 2026-05-01
[Literature Review] ends 2026-05-25
[Mid-Term Presentation] starts 2026-05-25
[Mid-Term Presentation] ends 2026-06-12
[Reproduce Previous Results] starts 2026-05-20
[Reproduce Previous Results] ends 2026-06-05
[Validation of Preliminary Results] starts 2026-06-05
[Validation of Preliminary Results] ends 2026-06-10
[Implement Proper Algorithm Settings and Improve Preliminary Results] starts 2026-06-10
[Implement Proper Algorithm Settings and Improve Preliminary Results] ends 2026-06-15
[Extend Experiment to Full Settings] starts 2026-06-15
[Extend Experiment to Full Settings] ends 2026-07-05
[Improve Experiment with Ablation Studies] starts 2026-07-05
[Improve Experiment with Ablation Studies] ends 2026-07-15
[Improve Algorithms by adding xxx] starts 2026-07-15
[Improve Algorithms by adding xxx] ends 2026-07-30
[Experiment and Algorithms Optimisation] starts 2026-07-31
[Experiment and Algorithms Optimisation] ends 2026-08-25
[Dissertation Writing] starts 2026-07-20
[Dissertation Writing] ends 2026-08-30
[Project Finish] happens at 2026-09-04

[Reproduce Previous Results] -> [Validation of Preliminary Results]
[Validation of Preliminary Results] -> [Implement Proper Algorithm Settings and Improve Preliminary Results]
[Implement Proper Algorithm Settings and Improve Preliminary Results] -> [Extend Experiment to Full Settings]
[Extend Experiment to Full Settings] -> [Improve Experiment with Ablation Studies]
[Improve Experiment with Ablation Studies] -> [Improve Algorithms by adding xxx]
[Improve Algorithms by adding xxx] -> [Experiment and Algorithms Optimisation]
[Dissertation Writing] -> [Project Finish]
@endgantt
