gantt
    title MSc Research Project - Risk-Aware SMPC for Autonomous Driving at Intersections
    dateFormat  YYYY-MM-DD
    axisFormat  %d
    tickInterval 1week
    todayMarker off

    section Task Name
    Literature Review                                      :lit, 2026-05-01, 2026-05-25
    Mid-Term Presentation                                 :mid, 2026-05-25, 2026-06-12
    Reproduce Previous Results                            :repr, 2026-05-20, 2026-06-05
    Validation of Preliminary Results                     :valid, after repr, 5d
    Implement Proper Algorithm Settings and Improve Preliminary Results :settings, after valid, 5d
    Extend Experiment to Full Settings                    :full, after settings, 20d
    Improve Experiment with Ablation Studies              :ablation, after full, 10d
    Improve Algorithms by adding xxx                      :algo, after ablation, 15d
    Experiment and Algorithms Optimisation                :optim, 2026-07-31, 2026-08-25
    Dissertation Writing                                  :writing, 2026-07-20, 2026-08-30
    Project Finish                                        :milestone, finish, after writing, 4d
