#!/usr/bin/env bash
set -euo pipefail

# 10-init supervisor ablation after supervisor feedback.
# Runs:
#   1) full supervisor: current baseline behaviour
#   2) reduced_intervention supervisor: keeps hard safety guard but reduces
#      unnecessary deterministic yield intervention so SMPC behaviour is more visible,
#      while retaining a post-clearance rejoin stabilisation guard.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPO_DIR="$(cd "${CORE_DIR}/.." && pwd)"
RESULTS_DIR="${RESULTS_DIR:-${CORE_DIR}/results/$(date +%Y%m%d_%H%M%S)_10init_supervisor_ablation}"
PYTHON_BIN="${PYTHON_BIN:-python}"
ENABLE_CAMERA_VIZ="${ENABLE_CAMERA_VIZ:-0}"
INIT_COUNT="${INIT_COUNT:-10}"
PREDICTION_MODEL_WEIGHTS="${PREDICTION_MODEL_WEIGHTS:-l5kit_multipath_10_carla_finetuned_head_best}"
PREDICTION_MODEL_ANCHORS="${PREDICTION_MODEL_ANCHORS:-l5kit_clusters_16.npy}"
SUPERVISOR_MODES="${SUPERVISOR_MODES:-full reduced_intervention}"

if [[ -z "${CARLA_ROOT:-}" ]]; then
  cat >&2 <<'EOF'
ERROR: CARLA_ROOT is not set.

Please export the CARLA 0.9.14 root before running this batch, for example:
  export CARLA_ROOT=/root/autodl-tmp/carla_0.9.14
EOF
  exit 2
fi

if [[ ! -f "${CARLA_ROOT}/PythonAPI/carla/agents/navigation/global_route_planner.py" ]]; then
  cat >&2 <<EOF
ERROR: CARLA Python agents were not found under:
  ${CARLA_ROOT}/PythonAPI/carla/agents
EOF
  exit 2
fi

export PYTHONPATH="${CARLA_ROOT}/PythonAPI/carla:${CARLA_ROOT}/PythonAPI/carla/agents:${PYTHONPATH:-}"

if [[ -z "${GUROBI_HOME:-}" && -d "${REPO_DIR}/gurobi/gurobi1103/linux64" ]]; then
  export GUROBI_HOME="${REPO_DIR}/gurobi/gurobi1103/linux64"
fi
if [[ -z "${GUROBI_VERSION:-}" ]]; then
  export GUROBI_VERSION="110"
fi
if [[ -z "${GRB_LICENSE_FILE:-}" && -f "${REPO_DIR}/gurobi/gurobi.lic" ]]; then
  export GRB_LICENSE_FILE="${REPO_DIR}/gurobi/gurobi.lic"
fi
if [[ -n "${GUROBI_HOME:-}" ]]; then
  export LD_LIBRARY_PATH="${GUROBI_HOME}/lib:${LD_LIBRARY_PATH:-}"
fi

"${PYTHON_BIN}" - <<'PY'
import os
import sys

import casadi as ca

ok = bool(ca.has_conic("gurobi"))
print(
    "CasADi/Gurobi preflight:",
    {
        "casadi": ca.__version__,
        "has_conic_gurobi": ok,
        "has_nlpsol_gurobi": bool(ca.has_nlpsol("gurobi")),
        "GUROBI_HOME": os.environ.get("GUROBI_HOME"),
        "GUROBI_VERSION": os.environ.get("GUROBI_VERSION"),
        "GRB_LICENSE_FILE": os.environ.get("GRB_LICENSE_FILE"),
    },
)
if not ok:
    print(
        "ERROR: CasADi conic Gurobi plugin is unavailable. "
        "This experiment uses ca.Opti('conic'), so ca.has_conic('gurobi') must be True.",
        file=sys.stderr,
    )
    sys.exit(2)
PY

MODEL_DIR="${CORE_DIR}/scripts/models/${PREDICTION_MODEL_WEIGHTS}"
if [[ "${PREDICTION_MODEL_WEIGHTS}" = /* ]]; then
  MODEL_DIR="${PREDICTION_MODEL_WEIGHTS}"
fi
if [[ ! -d "${MODEL_DIR}" ]]; then
  cat >&2 <<EOF
ERROR: prediction model directory not found:
  ${MODEL_DIR}

Set PREDICTION_MODEL_WEIGHTS to a model path or copy the fine-tuned model to core/scripts/models/.
EOF
  exit 2
fi

mkdir -p "${RESULTS_DIR}"
cd "${SCRIPT_DIR}"

camera_args=()
if [[ "${ENABLE_CAMERA_VIZ}" == "1" ]]; then
  camera_args+=(--enable_camera_viz)
else
  camera_args+=(--disable_camera_viz)
fi

TMP_INIT_DIR="${RESULTS_DIR}/_ego_init_01_${INIT_COUNT}"
mkdir -p "${TMP_INIT_DIR}"
for idx_num in $(seq 1 "${INIT_COUNT}"); do
  idx="$(printf '%02d' "${idx_num}")"
  ln -sfn "${SCRIPT_DIR}/scenarios/inits/paper_intersection_50/ego_init_${idx}.json" \
    "${TMP_INIT_DIR}/ego_init_${idx}.json"
done

make_tuning_config() {
  local mode="$1"
  local out_path="$2"
  "${PYTHON_BIN}" - "$mode" "$out_path" <<'PY'
import json
import sys

mode = sys.argv[1]
out_path = sys.argv[2]

config = {
    "config_name": f"supervisor_ablation_{mode}",
    "version": 1,
    "description": (
        "Supervisor ablation config generated by "
        "run_give_way_10init_supervisor_ablation.sh"
    ),
    "vehicle_role_overrides": {
        "ego": {
            "nominal_speed": 6.0,
            "N": 10,
            "dt": 0.2,
            "num_modes": 3,
            "collision_d_min": 0.5,
            "collision_ellipse_half_length": 3.8,
            "collision_ellipse_half_width": 1.8,
            "reference_regen_max_lateral_error": 1.5,
            "yield_stop_enabled": True,
            "yield_stop_speed": 0.2,
            "yield_caution_speed": 3.5,
            "yield_creep_speed": 1.5,
            "yield_caution_decel": -4.0,
            "yield_reference_min_speed": 0.8,
            "yield_reference_decel": -3.75,
            "yield_stop_decel": -5.0,
            "yield_emergency_brake_enabled": True,
            "yield_emergency_decel": -7.0,
            "yield_emergency_jerk_limit": 10.0,
            "yield_emergency_conflict_margin": 1.25,
            "yield_hard_stop_target_distance": 12.0,
            "yield_hard_stop_conflict_distance": 13.0,
            "yield_conflict_radius": 4.0,
            "yield_stop_buffer_distance": 7.0,
            "yield_footprint_clearance_margin": 1.5,
            "yield_brake_distance_margin": 3.5,
            "yield_wait_steer_lookahead_distance": 6.0,
            "yield_wait_steer_gain": 1.0,
            "yield_ttc_margin": 0.8,
            "yield_activation_distance": 12.0,
            "yield_hold_distance": 3.0,
            "yield_release_time": 0.3,
            "yield_release_clearance_margin": 1.0,
            "yield_observed_caution_enabled": True,
            "yield_observed_caution_distance": 12.0,
            "yield_observed_caution_min_target_speed": 0.5,
            "yield_steer_damping": 0.25,
            "yield_recovery_enabled": True,
            "yield_recovery_steps": 180,
            "yield_recovery_regen_period": 2,
            "yield_recovery_max_lateral_error": 12.0,
            "yield_recovery_speed": 5.5,
            "yield_recovery_accel": 1.8,
            "yield_supervisor_mode": mode,
        },
        "target": {
            "nominal_speed": 9.0,
            "init_speed": 9.0,
        },
    },
}

if mode == "reduced_intervention":
    ego = config["vehicle_role_overrides"]["ego"]
    # Keep reduced pre-clearance intervention, but retain enough post-clearance
    # rejoin window to stabilise route completion. This remains shorter and less
    # deterministic than the full supervisor.
    ego["yield_recovery_steps"] = 90
    ego["yield_release_clearance_margin"] = 0.5
    ego["yield_recovery_speed"] = 4.5
    ego["yield_recovery_accel"] = 1.0

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2)
    f.write("\n")
PY
}

run_mode() {
  local mode="$1"
  local label="$2"
  local mode_dir="${RESULTS_DIR}/${label}"
  local tuning_config="${RESULTS_DIR}/tuning_${label}.json"

  mkdir -p "${mode_dir}"
  make_tuning_config "${mode}" "${tuning_config}"

  echo "Running supervisor mode=${mode}; results=${mode_dir}"
  "${PYTHON_BIN}" run_all_scenarios.py \
    --scenario_glob "scenario_uk_give_way.json" \
    --init_glob "${TMP_INIT_DIR}/ego_init_*.json" \
    --results_dir "${mode_dir}" \
    --policies smpc_var_risk smpc_fixed_risk \
    --risk_profile adaptive_interaction_severity \
    --tuning_config "${tuning_config}" \
    --prediction_model_weights "${PREDICTION_MODEL_WEIGHTS}" \
    --prediction_model_anchors "${PREDICTION_MODEL_ANCHORS}" \
    "${camera_args[@]}" \
    --postprocess_no_plots

  if ! "${PYTHON_BIN}" "${CORE_DIR}/scripts/postcarla_trajectory_gate.py" "${mode_dir}"; then
    echo "WARNING: post-CARLA gate reported FAIL for ${mode}; continuing diagnostics." >&2
  fi
  if ! "${PYTHON_BIN}" "${CORE_DIR}/scripts/risk_by_conflict_distance.py" "${mode_dir}"; then
    echo "WARNING: risk-by-conflict-distance diagnostics failed for ${mode}; continuing." >&2
  fi
  if ! "${PYTHON_BIN}" "${REPO_DIR}/docs/paper/diagnose_supervisor_feedback_step1.py" \
    --results-dir "${mode_dir}"; then
    echo "WARNING: supervisor feedback diagnostics failed for ${mode}; continuing." >&2
  fi
}

for mode in ${SUPERVISOR_MODES}; do
  case "${mode}" in
    full)
      run_mode "full" "full_supervisor"
      ;;
    reduced_intervention)
      run_mode "reduced_intervention" "reduced_intervention_supervisor"
      ;;
    *)
      echo "ERROR: unsupported supervisor mode in SUPERVISOR_MODES: ${mode}" >&2
      exit 2
      ;;
  esac
done

cat > "${RESULTS_DIR}/README.txt" <<EOF
Supervisor ablation complete.

Subdirectories:
  Generated according to SUPERVISOR_MODES=${SUPERVISOR_MODES}

Compare:
  diagnostics_after_supervisor_feedback/step1_diagnostic_report.md
  postcarla_trajectory_gate.md
  risk_by_conflict_distance_summary.md
  paper_metrics_summary.md
EOF

echo "10-init supervisor ablation complete: ${RESULTS_DIR}"
